### ISSUE TITLE
Todo: Image Classification 

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/models#2196]
TODO: 
- [ ] Check image classification pre-trained models one more time, to make sure it's consistent with the architecture, such as: 
> why don't VGG pre-trained model have offset params meanwhile vgg.py support bias? 
> Need to update the code
- [x] some pre-trained models compressed on the mac, and will obtain redundancy folder: __MACOSX when decompressing on the Linux machine.
- [x] Unify filename, format: #2100 
- [ ] Bug: googlenet #2187 
- [x] Bug: resnet34 #2099

**Comment by shippingwang** [comment]
Summary:
- Update image classification pre-trained models.
Unified folder names
----

Format: 
> The model's name follows the camel case and join with a postfix: '_pretrained', like:  **AlexNet_pretrained**, **ShuffleNetV2**, upper 'N'et and 'V'ersion.

In every pre-trained folder, It has the whole trained parameters to support further works

1. AlexNet_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684285-10ad9b00-7668-11e9-8e03-8ad949f55a8c.png)
2. GoogleNet_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684517-86b20200-7668-11e9-96da-5de2d260254f.png)
3. MobileNetV1_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684568-9e898600-7668-11e9-85fa-54ebc26a4b2b.png)
4. MobileNetV2_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684643-c4168f80-7668-11e9-9daa-3a30a33bef04.png)
5. ResNet101_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684689-e0b2c780-7668-11e9-858c-9830d8d7f425.png)
6. ResNet152_pretrained 
too large to show
7. ResNet18_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684871-3e471400-7669-11e9-8f93-d9f9dc331d72.png)
8. ResNet34_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684899-4ef78a00-7669-11e9-9b72-928893112ca3.png)
9. ResNet50_pretrained
![image](https://user-images.githubusercontent.com/13645332/57684943-68003b00-7669-11e9-8f78-ed1bea087652.png)
10. SE_ResNeXt101_32x4d_pretrained
too large to show
11. SE_ResNeXt50_32x4d_pretrained
too large to show
12. ShuffleNetV2_pretrained
![image](https://user-images.githubusercontent.com/13645332/57685364-4b183780-766a-11e9-9002-e25ffe57434f.png)
13. VGG11_pretrained
![image](https://user-images.githubusercontent.com/13645332/57685389-59feea00-766a-11e9-9fab-0c55090eec79.png)
14. VGG13_pretrained
![image](https://user-images.githubusercontent.com/13645332/57685420-6b47f680-766a-11e9-9f17-2066b5fba70f.png)
15. VGG16_pretrained
![image](https://user-images.githubusercontent.com/13645332/57685445-7864e580-766a-11e9-92c1-1ae6e14baf71.png)
16. VGG19_pretrained
![image](https://user-images.githubusercontent.com/13645332/57685472-8d417900-766a-11e9-90db-36f72269ea8f.png)

**Comment by shippingwang** [comment]
- Delete useless __MACOSX file.
> compress on the MAC will obtain redundancy file. Update them now.
