### ISSUE TITLE
Todo: Image Classification

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/models#2305]
- [ ] refine image classification codes and docs in another repo: paddle/book
- [ ] https://github.com/PaddlePaddle/Paddle/issues/17149#issue-438126920
- [ ] update cv2 acc and cv2 reader

---
