### ISSUE TITLE
Summary of Bugs of V2 APIs

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#33]
- [x] Nested sequence is problematic in V2 https://github.com/PaddlePaddle/Paddle/issues/2065
- [x] Incorrect topological parsing with memory-layer https://github.com/PaddlePaddle/Paddle/issues/2061
- [ ] No check for static parameters. https://github.com/PaddlePaddle/Paddle/issues/2069
- [x] Some global parameters crucial for learning performance are not properly set https://github.com/PaddlePaddle/Paddle/issues/2042
- [x] Clipping can not work that makes training RNN model unstable https://github.com/PaddlePaddle/Paddle/issues/1894 https://github.com/PaddlePaddle/Paddle/issues/1961
- [x] Inference in V2 is slower than the old API https://github.com/PaddlePaddle/Paddle/issues/1961
- [ ] size and num_filters cannot be obtained in V2 APIs. https://github.com/PaddlePaddle/Paddle/issues/1811

Not supported
- [x] Multiplex Layer for scheduled sampling is not supported in v2. 
- [ ] Subsequence Layer https://github.com/PaddlePaddle/Paddle/issues/2026
- [x] Some element-wise computation https://github.com/PaddlePaddle/Paddle/issues/1790
- [ ] C-API not ready for V2 https://github.com/PaddlePaddle/Paddle/issues/1949

**Comment by QiJune** [comment]
Update "C-API not ready for V2"

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
